devmapper: Fix build error on 32bit host
This patch fixes the build error.

../grub-core/osdep/devmapper/getroot.c: In function
'grub_util_pull_devmapper':

../grub-core/osdep/devmapper/getroot.c:265:75: error: format '%lu'
expects argument of type 'long unsigned int', but argument 2 has type
'int' [-Werror=format=]

../grub-core/osdep/devmapper/getroot.c:276:80: error: format '%lu'
expects argument of type 'long unsigned int', but argument 2 has type
'int' [-Werror=format=]

Fixes: aa5172a55 (osdep/devmapper/getroot: Set up cheated LUKS2
cryptodisk mount from DM parameters)

Signed-off-by: Michael Chang <mchang@suse.com>